name: Process docs for SQLite AI Search

on:
  workflow_dispatch:
  
jobs:
  docsearch:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      
      - uses: sqliteai/sqlite-aisearch-action@v1
        with:
          connection_string: ${{ secrets.PROJECT_STRING }}
          base_url: ${{ vars.BASE_URL }}
          database_name: documentation_ai.sqlite
          source_files: ./
          only_extensions: "md,mdx"
