name: Process docs for SQLite AI Search

on:
  workflow_dispatch:
  
jobs:
  docsearch:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      
      # - uses: sqlitecloud/sqlite-ai-action@v1
      #   with:
      #     project-string: ${{ secrets.PROJECT_STRING }}
      #     base-url: ${{ vars.BASE_URL }}
      #     database: documentation_ai.sqlite
